// Données des 32 cartes Animaux (1-32) et 10 cartes Esprit de la Nature (33-42).
// Couleurs : 1 eau/bleu, 2 montagne/gris, 3 tronc/marron, 4 feuillage/vert, 5 champ/jaune, 6 bâtiment/rouge, 7 = base quelconque d'un bâtiment.
// pat : chaîne d'emplacements ; s = pile attendue (du haut vers le bas), d = direction depuis l'emplacement précédent (0-5), cube = emplacement du cube.
// pts : valeur de la carte selon le nombre de cubes posés (1er cube -> pts[0], etc.).
const CARDS = [
  {"id": 1, "fr": "Crocodile", "en": "Crocodile", "emoji": "🐊", "pts": [4, 9, 15], "pat": [{"s": [4, 3, 3], "d": 0, "cube": false}, {"s": [1], "d": 3, "cube": false}, {"s": [1], "d": 3, "cube": true}], "spirit": false},
  {"id": 2, "fr": "Raie", "en": "Ray", "emoji": "🐟", "pts": [4, 10, 16], "pat": [{"s": [2], "d": 0, "cube": false}, {"s": [2], "d": 4, "cube": false}, {"s": [1], "d": 2, "cube": true}], "spirit": false},
  {"id": 3, "fr": "Saumon", "en": "Salmon", "emoji": "🐠", "pts": [3, 6, 10, 16], "pat": [{"s": [2, 2, 2], "d": 0, "cube": false}, {"s": [1], "d": 3, "cube": true}], "spirit": false},
  {"id": 4, "fr": "Loutre", "en": "Otter", "emoji": "🦦", "pts": [5, 10, 16], "pat": [{"s": [4], "d": 0, "cube": false}, {"s": [4], "d": 3, "cube": false}, {"s": [1], "d": 3, "cube": true}], "spirit": false},
  {"id": 5, "fr": "Grenouille", "en": "Frog", "emoji": "🐸", "pts": [2, 4, 6, 10, 15], "pat": [{"s": [4], "d": 0, "cube": false}, {"s": [1], "d": 3, "cube": true}], "spirit": false},
  {"id": 6, "fr": "Canard", "en": "Duck", "emoji": "🦆", "pts": [2, 4, 8, 13], "pat": [{"s": [6, 7], "d": 0, "cube": false}, {"s": [1], "d": 3, "cube": true}], "spirit": false},
  {"id": 7, "fr": "Flamant rose", "en": "Flamingo", "emoji": "🦩", "pts": [4, 10, 16], "pat": [{"s": [5], "d": 0, "cube": false}, {"s": [1], "d": 3, "cube": true}, {"s": [5], "d": 5, "cube": false}], "spirit": false},
  {"id": 8, "fr": "Gecko", "en": "Gecko", "emoji": "🦎", "pts": [5, 10, 16], "pat": [{"s": [5], "d": 0, "cube": false}, {"s": [5], "d": 3, "cube": false}, {"s": [6, 7], "d": 3, "cube": true}], "spirit": false},
  {"id": 9, "fr": "Musaraigne", "en": "Shrew", "emoji": "🐭", "pts": [5, 10, 17], "pat": [{"s": [5], "d": 0, "cube": false}, {"s": [6, 7], "d": 2, "cube": true}, {"s": [5], "d": 3, "cube": false}], "spirit": false},
  {"id": 10, "fr": "Paon", "en": "Peacock", "emoji": "🦚", "pts": [5, 10, 17], "pat": [{"s": [1], "d": 0, "cube": false}, {"s": [6, 7], "d": 2, "cube": true}, {"s": [1], "d": 3, "cube": false}], "spirit": false},
  {"id": 11, "fr": "Écureuil", "en": "Squirrel", "emoji": "🐿️", "pts": [4, 9, 15], "pat": [{"s": [4, 3, 3], "d": 0, "cube": false}, {"s": [6, 7], "d": 3, "cube": true}], "spirit": false},
  {"id": 12, "fr": "Hérisson", "en": "Hedgehog", "emoji": "🦔", "pts": [5, 12], "pat": [{"s": [4, 3], "d": 0, "cube": false}, {"s": [6, 7], "d": 3, "cube": true}, {"s": [4, 3], "d": 5, "cube": false}], "spirit": false},
  {"id": 13, "fr": "Abeille", "en": "Bee", "emoji": "🐝", "pts": [8, 18], "pat": [{"s": [5], "d": 0, "cube": false}, {"s": [4, 3], "d": 2, "cube": true}, {"s": [5], "d": 4, "cube": false}, {"s": [5], "d": 2, "cube": false}], "spirit": false},
  {"id": 14, "fr": "Ours", "en": "Bear", "emoji": "🐻", "pts": [5, 11], "pat": [{"s": [2, 2], "d": 0, "cube": false}, {"s": [4], "d": 3, "cube": true}, {"s": [2, 2], "d": 5, "cube": false}], "spirit": false},
  {"id": 15, "fr": "Lapin", "en": "Rabbit", "emoji": "🐰", "pts": [5, 10, 17], "pat": [{"s": [6, 7], "d": 0, "cube": false}, {"s": [4], "d": 3, "cube": false}, {"s": [4], "d": 3, "cube": true}], "spirit": false},
  {"id": 16, "fr": "Ara", "en": "Macaw", "emoji": "🦜", "pts": [4, 9, 14], "pat": [{"s": [1], "d": 0, "cube": false}, {"s": [4, 3], "d": 3, "cube": true}, {"s": [1], "d": 5, "cube": false}], "spirit": false},
  {"id": 17, "fr": "Sanglier", "en": "Boar", "emoji": "🐗", "pts": [4, 8, 13], "pat": [{"s": [6, 7], "d": 0, "cube": false}, {"s": [4, 3], "d": 3, "cube": true}], "spirit": false},
  {"id": 18, "fr": "Koala", "en": "Koala", "emoji": "🐨", "pts": [3, 6, 10, 15], "pat": [{"s": [4], "d": 0, "cube": false}, {"s": [4, 3], "d": 3, "cube": true}], "spirit": false},
  {"id": 19, "fr": "Loup", "en": "Wolf", "emoji": "🐺", "pts": [4, 10, 16], "pat": [{"s": [5], "d": 0, "cube": false}, {"s": [4, 3, 3], "d": 3, "cube": true}, {"s": [5], "d": 5, "cube": false}], "spirit": false},
  {"id": 20, "fr": "Martin-pêcheur", "en": "Kingfisher", "emoji": "🐦", "pts": [5, 11, 18], "pat": [{"s": [1], "d": 0, "cube": false}, {"s": [4, 3, 3], "d": 2, "cube": true}, {"s": [1], "d": 3, "cube": false}], "spirit": false},
  {"id": 21, "fr": "Manchot", "en": "Penguin", "emoji": "🐧", "pts": [4, 10, 16], "pat": [{"s": [1], "d": 0, "cube": false}, {"s": [2], "d": 2, "cube": true}, {"s": [1], "d": 3, "cube": false}], "spirit": false},
  {"id": 22, "fr": "Chauve-souris", "en": "Bat", "emoji": "🦇", "pts": [3, 6, 10, 15], "pat": [{"s": [4, 3, 3], "d": 0, "cube": false}, {"s": [2], "d": 3, "cube": true}], "spirit": false},
  {"id": 23, "fr": "Fennec", "en": "Fennec", "emoji": "🦊", "pts": [4, 9, 16], "pat": [{"s": [5], "d": 0, "cube": false}, {"s": [2], "d": 3, "cube": false}, {"s": [2], "d": 3, "cube": true}], "spirit": false},
  {"id": 24, "fr": "Macaque", "en": "Macaque", "emoji": "🐒", "pts": [5, 11], "pat": [{"s": [1], "d": 0, "cube": false}, {"s": [2, 2], "d": 3, "cube": true}, {"s": [1], "d": 5, "cube": false}], "spirit": false},
  {"id": 25, "fr": "Bateleur", "en": "Bateleur", "emoji": "🦅", "pts": [5, 11], "pat": [{"s": [5], "d": 0, "cube": false}, {"s": [2, 2, 2], "d": 3, "cube": true}], "spirit": false},
  {"id": 26, "fr": "Suricate", "en": "Meerkat", "emoji": "🐾", "pts": [2, 5, 9, 14], "pat": [{"s": [5], "d": 0, "cube": false}, {"s": [2], "d": 3, "cube": true}], "spirit": false},
  {"id": 27, "fr": "Corbeau", "en": "Crow", "emoji": "🐦‍⬛", "pts": [4, 9], "pat": [{"s": [6, 7], "d": 0, "cube": false}, {"s": [5], "d": 2, "cube": true}, {"s": [6, 7], "d": 3, "cube": false}], "spirit": false},
  {"id": 28, "fr": "Alpaga", "en": "Alpaca", "emoji": "🦙", "pts": [5, 12], "pat": [{"s": [2, 2], "d": 0, "cube": false}, {"s": [5], "d": 3, "cube": false}, {"s": [5], "d": 3, "cube": true}], "spirit": false},
  {"id": 29, "fr": "Renard polaire", "en": "Arctic fox", "emoji": "❄️", "pts": [5, 10, 17], "pat": [{"s": [4, 3], "d": 0, "cube": false}, {"s": [5], "d": 2, "cube": true}, {"s": [4, 3], "d": 3, "cube": false}], "spirit": false},
  {"id": 30, "fr": "Raton laveur", "en": "Raccoon", "emoji": "🦝", "pts": [6, 12], "pat": [{"s": [1], "d": 0, "cube": false}, {"s": [5], "d": 2, "cube": true}, {"s": [1], "d": 4, "cube": false}, {"s": [1], "d": 2, "cube": false}], "spirit": false},
  {"id": 31, "fr": "Coccinelle", "en": "Ladybug", "emoji": "🐞", "pts": [2, 5, 8, 12, 17], "pat": [{"s": [4], "d": 0, "cube": false}, {"s": [5], "d": 3, "cube": true}], "spirit": false},
  {"id": 32, "fr": "Panthère", "en": "Panther", "emoji": "🐆", "pts": [5, 11], "pat": [{"s": [4, 3], "d": 0, "cube": false}, {"s": [4, 3], "d": 3, "cube": false}, {"s": [5], "d": 3, "cube": true}], "spirit": false},
  {"id": 33, "fr": "Lion", "en": "Lion", "emoji": "🦁", "pts": [], "pat": [{"s": [4, 3], "d": 0, "cube": false}, {"s": [5], "d": 3, "cube": true}, {"s": [5], "d": 3, "cube": false}], "spirit": true, "rule": "10 pts par groupe de 3 jetons jaunes ou plus, 2 pts par groupe de 1 ou 2"},
  {"id": 34, "fr": "Papillon", "en": "Butterfly", "emoji": "🦋", "pts": [], "pat": [{"s": [5], "d": 0, "cube": false}, {"s": [1], "d": 2, "cube": false}, {"s": [1], "d": 4, "cube": false}, {"s": [5], "d": 2, "cube": true}], "spirit": true, "rule": "5 pts par groupe de jetons jaunes (taille quelconque)"},
  {"id": 35, "fr": "Élan", "en": "Elk", "emoji": "🫎", "pts": [], "pat": [{"s": [4, 3, 3], "d": 0, "cube": false}, {"s": [4, 3], "d": 3, "cube": true}, {"s": [4], "d": 3, "cube": false}], "spirit": true, "rule": "4 pts par arbre de hauteur 2 ou 3"},
  {"id": 36, "fr": "Hibou", "en": "Owl", "emoji": "🦉", "pts": [], "pat": [{"s": [4], "d": 0, "cube": false}, {"s": [4, 3, 3], "d": 3, "cube": true}, {"s": [4], "d": 5, "cube": false}], "spirit": true, "rule": "3 pts par arbre de hauteur 1 ou 2, 1 pt par arbre de hauteur 3"},
  {"id": 37, "fr": "Chat", "en": "Cat", "emoji": "🐈", "pts": [], "pat": [{"s": [6, 7], "d": 0, "cube": false}, {"s": [4], "d": 3, "cube": false}, {"s": [6, 7], "d": 3, "cube": true}], "spirit": true, "rule": "4 pts par groupe de bâtiments (taille quelconque)"},
  {"id": 38, "fr": "Cigogne", "en": "Stork", "emoji": "🕊️", "pts": [], "pat": [{"s": [5], "d": 0, "cube": false}, {"s": [6, 7], "d": 3, "cube": false}, {"s": [6, 7], "d": 3, "cube": true}], "spirit": true, "rule": "6 pts par groupe de 2 bâtiments ou plus"},
  {"id": 39, "fr": "Bélier", "en": "Ram", "emoji": "🐏", "pts": [], "pat": [{"s": [2, 2], "d": 0, "cube": false}, {"s": [2, 2, 2], "d": 3, "cube": true}], "spirit": true, "rule": "4 pts par montagne de hauteur 2 ou 3 (même isolée)"},
  {"id": 40, "fr": "Castor", "en": "Beaver", "emoji": "🦫", "pts": [], "pat": [{"s": [2], "d": 0, "cube": false}, {"s": [2, 2], "d": 2, "cube": true}, {"s": [2], "d": 3, "cube": false}], "spirit": true, "rule": "3 pts par montagne de hauteur 1 ou 2, 1 pt par montagne de hauteur 3 (même isolée)"},
  {"id": 41, "fr": "Libellule", "en": "Dragonfly", "emoji": "🪰", "pts": [], "pat": [{"s": [4, 3], "d": 0, "cube": false}, {"s": [1], "d": 3, "cube": true}, {"s": [4, 3], "d": 3, "cube": false}], "spirit": true, "rule": "7 pts par groupe de 2 jetons bleus ou plus"},
  {"id": 42, "fr": "Tortue", "en": "Tortoise", "emoji": "🐢", "pts": [], "pat": [{"s": [2, 2], "d": 0, "cube": false}, {"s": [1], "d": 3, "cube": true}, {"s": [1], "d": 3, "cube": false}], "spirit": true, "rule": "2 pts par jeton bleu"},
];
if (typeof module !== 'undefined') module.exports = { CARDS };
else if (typeof self !== 'undefined') self.CARDS = CARDS;
